### ISSUE TITLE
Datepicker not formatting on re-load

### ISSUE THREAD

**Issue by GotWoods** [fizker/date-picker#2]
It seems if you use a different format that clicking a textbox will show the wrong date in the calendar.

It seems the fix is on line 403:
parseDate(this._elms.input.value) || this.options.date;

by adding the format it fixes it:
parseDate(this._elms.input.value, this.options.dateFormat) || this.options.date;

Thoughts?

**Comment by fizker** [comment]
Hm. That does make sense. I'll push it later today.
